package org.sideloader;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.ArrayList;
import java.util.Locale;

public class FeaturedApps extends JPanel {
    private JPanel panel1;
    private JButton program1;
    private JButton program2;
    private JButton program3;
    private JButton program4;
    private JButton program5;
    private JButton program6;
    private JLabel attractText;

    public FeaturedApps(JScrollPane storeContentPane) {
        panel1.setPreferredSize(new Dimension(900, 900));
        add(panel1);

        for (JButton button : new JButton[]{program1, program2, program3, program4, program5, program6}) {
            button.addActionListener((e) -> {
                storeContentPane.setViewportView(new LoadingPanel(storeContentPane)); //show loading panel while loading
                SnapSideloaderStore.loadSelectedProgram(button, storeContentPane, this);
            });
        }

    }

    public void setWelcomeText(String text) {
        attractText.setText(text);
    }

    public void populateFeaturedApps(ArrayList<String> programs, ArrayList<String> packageNames, ArrayList<String> summaries, ArrayList<String> iconURLs) { //populate each button depending on how many featured apps/programs there are
        JButton[] buttons = {program1, program2, program3, program4, program5, program6};
        for (int i = 0; i < programs.size(); i++) {
            SnapSideloaderStore.styleButton(buttons[i], programs.get(i), packageNames.get(i), summaries.get(i), iconURLs.get(i));
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(7, 1, new Insets(0, 0, 0, 0), -1, -1));
        program2 = new JButton();
        program2.setEnabled(false);
        Font program2Font = this.$$$getFont$$$(null, -1, 20, program2.getFont());
        if (program2Font != null) program2.setFont(program2Font);
        program2.setText("<...>");
        panel1.add(program2, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        program1 = new JButton();
        program1.setEnabled(false);
        Font program1Font = this.$$$getFont$$$(null, -1, 20, program1.getFont());
        if (program1Font != null) program1.setFont(program1Font);
        program1.setText("<...>");
        panel1.add(program1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        program3 = new JButton();
        program3.setEnabled(false);
        Font program3Font = this.$$$getFont$$$(null, -1, 20, program3.getFont());
        if (program3Font != null) program3.setFont(program3Font);
        program3.setText("<...>");
        panel1.add(program3, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        program4 = new JButton();
        program4.setEnabled(false);
        Font program4Font = this.$$$getFont$$$(null, -1, 20, program4.getFont());
        if (program4Font != null) program4.setFont(program4Font);
        program4.setText("<...>");
        panel1.add(program4, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        program5 = new JButton();
        program5.setEnabled(false);
        Font program5Font = this.$$$getFont$$$(null, -1, 20, program5.getFont());
        if (program5Font != null) program5.setFont(program5Font);
        program5.setText("<...>");
        panel1.add(program5, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        program6 = new JButton();
        program6.setEnabled(false);
        Font program6Font = this.$$$getFont$$$(null, -1, 20, program6.getFont());
        if (program6Font != null) program6.setFont(program6Font);
        program6.setText("<...>");
        panel1.add(program6, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        attractText = new JLabel();
        Font attractTextFont = this.$$$getFont$$$("Ubuntu", Font.BOLD, 36, attractText.getFont());
        if (attractTextFont != null) attractText.setFont(attractTextFont);
        attractText.setText("Featured programs:");
        panel1.add(attractText, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
